CREATE TABLE friends (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id1 INT REFERENCES users NOT NULL,
    user_id2 INT REFERENCES users NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL
);